### ISSUE TITLE
logout button will disappear when using touch ID

### ISSUE THREAD

**Issue by braincover** [rolandleth/LTHPasscodeViewController#131] opened 2015-10-27 07:37 UTC
Logout button and navBar will be removed when I cancel the touch ID alert ( by _resetUI ), then I will trapped in passcode view if I haven't handle maxNumberOfFailedAttemptsReached.

**Comment by rolandleth** [comment] 2016-01-29 12:22
I will look into it, but `maxNumberOfFailedAttemptsReached` shouldn't be left unhandled, in my opinion.

**Comment by rolandleth** [comment] 2016-01-29 12:49
Can you check the latest build, please? `3.7.4`.

**Comment by rolandleth** [comment] 2016-02-01 11:52
@braincover Can I close the issue?

**Comment by rolandleth** [comment] 2016-02-03 16:58
Since I can't reproduce the issue and there has been no reply in the past week, I'm going to close the issue.

**Closed by rolandleth** 2016-02-03 16:58 UTC
