### ISSUE TITLE
Add info for use with storyboards

### ISSUE THREAD

**Issue by blwinters** [rolandleth/LTHPasscodeViewController#172] opened 2016-12-20 13:32 UTC
For a while I couldn't figure out why the `LTHPasscodeViewController` was showing up inconsistently. I thought my problem was related to #145. Then I changed my storyboard initialization process (in order to immediately show a login screen over my `UITabBarViewController` after launch), and now it's working beautifully. I recommend that you add some info to the How To Use section of the README for use with storyboards.

For me, I had to remove the storyboard name from Target > General > Deployment Info > Main Interface.
![screen shot 2016-12-20 at 8 20 34 am](https://cloud.githubusercontent.com/assets/4462923/21351949/4604ecd2-c68d-11e6-8453-e6c689a76a6e.png)

Then in `application(didFinishLaunchingWithOptions:)`

    window = UIWindow(frame: UIScreen.main.bounds)
    if let window = window { //setup rootViewController manually instead of using storyboard so that PasscodeViewController can be shown immediately
        window.backgroundColor = UIColor.white
        window.rootViewController = UIStoryboard(name: "Main", bundle: Bundle.main).instantiateInitialViewController()
        window.makeKeyAndVisible()
    }

    //setup passcode appearance...

    if LTHPasscodeViewController.doesPasscodeExist() && LTHPasscodeViewController.didPasscodeTimerEnd() {
        LTHPasscodeViewController.sharedUser().showLockScreen(withAnimation: false, withLogout: false, andLogoutTitle: nil)
    }

**Comment by rolandleth** [comment] 2016-12-20 13:39
Hey Ben,


Thank you for your input and help, but, sadly, I don't use Storyboards, so the support for them is ... unofficial; it was added by a user. That means I have no idea if your scenario is a standard one, or a special case, because if it is, it can't really be added to the README. Is removing the `Main` something usual? When using Storyboards, isn't that the *entry point* of the app?

I would definitely like to add something to the README, since it would help developers, but it would have to be something that generally applies to (almost) everyone.

**Comment by blwinters** [comment] 2016-12-20 16:41
I've only been using this approach for a couple weeks, but it works fine and I originally saw it in a project by another developer. Here is a [StackOverflow link](http://stackoverflow.com/questions/22653993/programatically-change-rootviewcontroller-of-storyboard) about the topic. 

My understanding is that programmatically setting `window.rootViewController = UIStoryboard(...)` does the exact same thing as entering the storyboard name in the Deployment Info. However, doing it programmatically gives us more control over the order of which view controller is shown first. It doesn't affect the functionality of storyboards.

**Comment by rolandleth** [comment] 2016-12-20 20:54
Hey Ben,


I see, and it makes total sense. But the problem is that if this isn't a familiar / spread approach, it would be kinda wrong to recommend it in the README. I will leave the issue open for a while, add some labels, and maybe we'll get some more feedback on this.

**Comment by blwinters** [comment] 2016-12-20 21:55
Sure, that sounds good. I'd also like to know if the community has more information on the implications of this.

**Comment by rolandleth** [comment] 2017-12-01 09:40
Almost a year has passed, no outside input was received, and I still don't work with Storyboard :)

I added a short description pointing to this issue, maybe others will find the info useful, and I can also close the issue.

Thank you!

**Closed by rolandleth** 2017-12-01 09:40 UTC
Labels: enhancement, needs help, question
