### ISSUE TITLE
Keyboard not coming up?

### ISSUE THREAD

**Issue by SunnyShah407** [rolandleth/LTHPasscodeViewController#162] opened 2016-10-25 12:04 UTC
When you first time open LTHPasscodeViewController it open keyboard. now when you press home button and come back keyboard not coming up.

**Comment by rolandleth** [comment] 2016-10-25 12:12
Can you reproduce it in the demo app? For me it's working, you just need to _Toggle Soft Keyboard `(command K)`_

**Comment by SunnyShah407** [comment] 2016-10-25 12:21
I am using device not simulator. its simple just press home button and come back

**Comment by rolandleth** [comment] 2016-10-25 12:30
OK, but can you reproduce it on the demo app? Because for me it's working.

**Comment by SunnyShah407** [comment] 2016-10-25 12:46
Its my mistake. I am presenting viewcontroller every time. fixed using 

  if (self.isCurrentlyOnScreen) {
        return;
    }

On - (void)showLockScreenWithAnimation:(BOOL)animated withLogout:(BOOL)hasLogout andLogoutTitle:(NSString*)logoutTitle; method

**Comment by rolandleth** [comment] 2016-10-25 12:48
But that method already has that check, internally 😕

Can I close the issue?

**Closed** 2016-10-25 13:18 UTC
