### ISSUE TITLE
Call to showLockScreenWithAnimation method on Change passcode screen doesn't display lock screen

### ISSUE THREAD

**Issue by DimaSlk** [rolandleth/LTHPasscodeViewController#167] opened 2016-10-28 09:59 UTC
I needed to add a screen locking by timeout (user inactivity). So I added a timer which calls showLockScreenWithAnimation method after user inactive due to timeout duration.

It works except _Change Passcode_ screen when it's not **modal**.

Steps to reproduce in Demo application:
- change `_changePasscode` method of `LTHDemoViewController.m` class to

`- (void)_changePasscode {`

```
[self showLockViewForChangingPasscode];

[NSTimer scheduledTimerWithTimeInterval:10.0
                                 target:self
                               selector:@selector(showLockViewForTestingPasscode)
                               userInfo:nil
                                repeats:NO];
```

`}`
- open Demo application;
- turn off Touch ID;
- press Change button;
- wait for 10 seconds;

Actual result: Change passcode screen is gone and you redirected to the main screen but without prompting of entering a passcode.

If TouchID is enabled you will see an '_Unlock using Touch ID_' popup but you can press "Cancel" button and lock screen is not displayed.

It is not reproduced if _Change passcode_ screen is **modal**.

**Comment by rolandleth** [comment] 2016-10-31 10:03
Hey,


Hmm, this isn't really a bug. The problem is that the change controller is popped, and a new controller is being pushed basically at the same time. It's a bit tricky to handle this scenario from within, because while `_cancelAndDismissMe` does call `dismiss` or `pop`, it does so animated, and there's no proper way to check if we're closing because a new instance wants to be presented (and we'd call without animation), or we're simply closing (and we'd call with animation).

I think you have an edge case that you need to handle by yourself, and what I'd suggest is, for example, to call an intermediate `showLockscreenAfterInactivity` which would pop the current controller and present a new one (and you decided if there's an animation, and when, or not).

**Comment by rolandleth** [comment] 2016-11-11 08:59
@DimaSlk Have you solved the issue? Can I close this one?

**Comment by DimaSlk** [comment] 2016-11-14 08:29
Yes, you can close it. I found a way how to avoid it.

**Comment by rolandleth** [comment] 2016-11-14 17:35
Thank you, glad you found a solution!

**Closed by rolandleth** 2016-11-14 17:35 UTC
