### ISSUE TITLE
iOS 8 layout wrong

### ISSUE THREAD

**Issue by MaxHasADHD** [rolandleth/LTHPasscodeViewController#74] opened 2014-08-17 17:13 UTC
On iOS 8 the passcode bubbles appear in the top left. Probably changes in auto layout or something messed it up.

**Comment by stoncle** [comment] 2015-01-03 06:49
The rotation act abnormally because the status bar **orientation observers are removed** in `_dismissMe` method, and after this, they are **not added** again, so the view won't rotate after the first passcode view dismissing(only at the first time the passcode view would rotate.

To fix this, the only thing we have to do is, move the "addObserver" code which related to status bar orientation from the `_addObserver` method(the last 2) to `viewWillAppear:` method. This shall fix the rotation problem! 

Hope this could help u.

**Comment by rolandleth** [comment] 2015-01-19 08:20
Added the code in the latest version, thanks! Do you think I can close this, or does it require further testing? I didn't have anything else besides an iPhone 6 to test it on.

**Comment by stoncle** [comment] 2015-01-20 14:32
well, there still exists some problems in rotation methods. In some cases, the desiredOrientation didn't return the correct orientation. It isn't a big problem, but it actually exists.(for example, rotate after clicking the cancel).

**Comment by QuachTam** [comment] 2015-04-22 07:45
WHEN YOU ENTER WRONG PASSCODE--> MESSAGE IS OVERRIDDEN BY VIRTUAL KEYBOARD

**Comment by rolandleth** [comment] 2015-10-20 09:57
Fixed in `3.6.8`.

**Closed by rolandleth** 2015-10-20 09:57 UTC

**Comment by 6axter82** [comment] 2017-08-14 17:11
Hi,I have got to views A and B.  I'm getting problem with my iPad version of a "change passcode" view, which is B. The first time I am going from A to B the layout is shown correctly, just as I expect. Than I press back button which brings me to view A and I rotate the iPad. After going again to the view B ("change passcode" view) I get the blank screen. 

Applying        
     LTHPasscodeViewController.sharedUser().updateViewConstraints()          
did not improve the situation much. Do you have any suggestions what to do?

**Comment by rolandleth** [comment] 2017-08-14 21:16
Hey,

Can you reproduce the bug in the demo app? If yes, can you provide a sample project based on the demo app(preferred)/steps to reproduce, please? Would be easier to track down the issue.

Maybe `LTHPasscodeViewController.sharedUser().view.layoutIfNeeded()`?

**Comment by 6axter82** [comment] 2017-08-18 12:49
Hi again,

yes, I did test the demo app and it gives the same result like in my app. 
Also the 'LTHPasscodeViewController.sharedUser().view.layoutIfNeeded()' proposed from you didn't do the trick :(

**Comment by rolandleth** [comment] 2017-08-18 12:56
Hey,

OK, can you provide a sample project based on the demo app, so I can try and debug it, please? Preferably a GitHub repo/fork with a new branch.

Thanks!

**Comment by 6axter82** [comment] 2017-08-18 14:39
I guess you just use the demo project. and run it on the iPad , could also be a simulator.
Steps to reproduce after you run in the simulator or on an actual device:
1) set the passcode
2) go to change it, but don't do that and press cancel instead, it will bring you back to the initial view
3) rotate device, go again to change the passcode
Result: you will see the empty screen
4) rotate the device or simulator again in the same view and everything comes to the place

**Comment by rolandleth** [comment] 2017-08-18 14:40
Thanks! Will investigate today, hopefully.

**Comment by rolandleth** [comment] 2017-08-19 17:18
Hey,

Added a fix in the latest commit, could you please have a look? Looks fine on my end, but I'd rather have another confirmation. Thanks!

**Comment by 6axter82** [comment] 2017-08-21 12:26
Hey, 

works perfectly now. I tested only on the demo app from you, on simulator and an actual device.

Could it be your commit is there but it is not tagged? I run 'pod update' but no changes come from github. Can you add it to the next stable release such that it updates using Podfile.

**Comment by rolandleth** [comment] 2017-08-21 12:29
I didn't update the pod just yet, I wanted to make sure everything is OK first. I will updated it later today. Thanks for confirming!

**Comment by 6axter82** [comment] 2017-08-22 08:19
@rolandleth hi, did you have a chance to update the pod?

**Comment by rolandleth** [comment] 2017-08-22 11:09
Done.

**Comment by 6axter82** [comment] 2017-08-22 12:09
awesome, thank you very much again!
